export interface Artistas {
  artistas: artista[];
}

interface artista {
  id: number;
  nombre: string;
}

export const artistas: Artistas = {
  artistas: [
    { id: 1, nombre: 'The Beatles' },
    { id: 2, nombre: 'Queen' },
    { id: 3, nombre: 'The Rolling Stones' },
    { id: 4, nombre: 'The Who' },
    { id: 5, nombre: 'The Doors' },
    { id: 6, nombre: 'Pink Floyd' },
    { id: 7, nombre: 'Led Zeppelin' },
    { id: 8, nombre: 'AC/DC' },
    { id: 9, nombre: 'Nirvana' },
    { id: 10, nombre: 'Metallica' },
    { id: 11, nombre: 'Red Hot Chili Peppers' },
    { id: 12, nombre: 'The Eagles' },
    { id: 13, nombre: 'U2' },
    { id: 14, nombre: 'Radiohead' },
    { id: 15, nombre: 'Pearl Jam' },
    { id: 16, nombre: 'The Clash' },
    { id: 17, nombre: "Guns N' Roses" },
    { id: 18, nombre: 'The Smiths' },
    { id: 19, nombre: 'Oasis' },
    { id: 20, nombre: 'Arctic Monkeys' },
    { id: 21, nombre: 'Foo Fighters' },
    { id: 22, nombre: 'The Strokes' },
    { id: 23, nombre: 'Coldplay' },
    { id: 24, nombre: 'The Killers' },
    { id: 25, nombre: 'Green Day' },
    { id: 26, nombre: 'R.E.M.' },
    { id: 27, nombre: 'The Police' },
    { id: 28, nombre: 'Deep Purple' },
    { id: 29, nombre: 'Black Sabbath' },
    { id: 30, nombre: 'Bon Jovi' },
    { id: 31, nombre: 'The Beach Boys' },
    { id: 32, nombre: 'Fleetwood Mac' },
    { id: 33, nombre: 'David Bowie' },
    { id: 34, nombre: 'The Velvet Underground' },
    { id: 35, nombre: 'The Kinks' },
    { id: 36, nombre: 'Yes' },
    { id: 37, nombre: 'Genesis' },
    { id: 38, nombre: 'The Cure' },
    { id: 39, nombre: 'Alice In Chains' },
    { id: 40, nombre: 'Soundgarden' },
    { id: 41, nombre: 'Kiss' },
    { id: 42, nombre: 'Def Leppard' },
    { id: 43, nombre: 'The Smashing Pumpkins' },
    { id: 44, nombre: 'Journey' },
    { id: 45, nombre: 'Rush' },
    { id: 46, nombre: 'Motörhead' },
    { id: 47, nombre: 'Slayer' },
    { id: 48, nombre: 'Iron Maiden' },
    { id: 49, nombre: 'Dream Theater' },
    { id: 50, nombre: 'The White Stripes' },
    { id: 51, nombre: 'Héroes del Silencio' },
    { id: 52, nombre: 'Joaquín Sabina' },
    { id: 53, nombre: 'Paco de Lucía' },
    { id: 54, nombre: 'Rosalía' },
    { id: 55, nombre: 'Extremoduro' },
    { id: 56, nombre: 'Fito & Fitipaldis' },
    { id: 57, nombre: 'Los Rodríguez' },
    { id: 58, nombre: 'Leiva' },
    { id: 59, nombre: 'Duncan Dhu' },
    { id: 60, nombre: 'Mecano' },
    { id: 61, nombre: 'La Oreja de Van Gogh' },
    { id: 62, nombre: 'Amaral' },
    { id: 63, nombre: 'El Canto del Loco' },
    { id: 64, nombre: 'Vetusta Morla' },
    { id: 65, nombre: 'Izal' },
    { id: 66, nombre: 'Marea' },
    { id: 67, nombre: 'Platero y Tú' },
    { id: 68, nombre: 'Los Secretos' },
    { id: 69, nombre: 'Antonio Vega' },
    { id: 70, nombre: 'Quique González' },
    { id: 71, nombre: 'Pereza' },
    { id: 72, nombre: 'Dover' },
    { id: 73, nombre: 'Ska-P' },
    { id: 74, nombre: 'Jarabe de Palo' },
    { id: 75, nombre: 'Celtas Cortos' },
    { id: 76, nombre: 'Estopa' },
    { id: 77, nombre: 'Kiko Veneno' },
    { id: 78, nombre: 'Los Suaves' },
    { id: 79, nombre: 'Barón Rojo' },
    { id: 80, nombre: 'Obús' },
    { id: 81, nombre: 'Ángel Stanich' },
    { id: 82, nombre: 'Andrés Calamaro' },
    { id: 83, nombre: 'Zahara' },
    { id: 84, nombre: 'Iván Ferreiro' },
    { id: 85, nombre: 'Sidonie' },
    { id: 86, nombre: 'Love of Lesbian' },
    { id: 87, nombre: 'Deluxe' },
    { id: 88, nombre: 'Bunbury' },
    { id: 89, nombre: 'Rosendo' },
    { id: 90, nombre: 'Lori Meyers' },
    { id: 91, nombre: 'Supersubmarina' },
    { id: 92, nombre: 'Manolo García' },
    { id: 93, nombre: 'Macaco' },
    { id: 94, nombre: 'Txarrena' },
    { id: 95, nombre: 'Albert Pla' },
    { id: 96, nombre: 'Nacha Pop' },
    { id: 97, nombre: 'Hombres G' },
    { id: 98, nombre: 'Revólver' },
    { id: 99, nombre: 'Bebe' },
    { id: 100, nombre: 'Miguel Ríos' },
  ],
};
